### PR TITLE
Fix mobile-view text overlapping

### PR DESCRIPTION
**Pull request by kevalnagda**

### CODE REVIEW

**Comment by ExpressHermes** [comment]
@pumpkinman008 This issue is not assigned to you. Someone else is working on it. I am closing this.

**Comment by kevalnagda** [comment]
@ExpressHermes It was a small fix and the assignee had not responded in 8 days. That's why I picked it. Sorry if I violated something.
Also, I understand that it was not assigned to me but you didn't have to tag it as invalid.

**Comment by ExpressHermes** [comment]
@pumpkinman008 You have not violated any rule. I get your point. If the person to whom the issue has been assigned does not respond within a week, I will merge your PR. I am removing the invalid label.

**Comment by kevalnagda** [comment]
Sure, @ExpressHermes . That sounds good. Thank you!!

**Review by ExpressHermes — APPROVED** [review]

**Pull request merged**
